# Generated by Django 5.1.6 on 2025-03-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('origin_name', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('api_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
