# Generated by Django 5.1.6 on 2025-03-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_location_character_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='residents_count',
            field=models.IntegerField(default=0),
        ),
    ]
