# Generated by Django 5.1.6 on 2025-03-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_location_residents_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='location',
            name='type',
        ),
    ]
